apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "${name}"
  namespace: "${namespace}"
spec:
  schedule: "${schedule}"
  jobTemplate:
    metadata:
      labels:
        app: "${name}"
    spec:
      template:
        metadata:
          labels:
            app: "${name}"
        spec:
          containers:
          - name: "${name}"
            image: "${image}"
            env: ${env_json}
          security_context:
            capabilities:
              add: ${capabilities_json}
